title: Invoke-Obfuscation CLIP+ Launcher
id: 4edf51e1-cb83-4e1a-bc39-800e396068e3
related:
    - id: f7385ee2-0e0c-11eb-adc1-0242ac120002
      type: derived
description: Detects Obfuscated use of Clip.exe to execute PowerShell
status: experimental
author: Jonathan Cheong, oscd.community
date: 2020/10/13
modified: 2021/09/16
references:
     - https://github.com/Neo23x0/sigma/issues/1009 #(Task 26)
tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001

logsource:
    product: windows
    service: security
detection:
    selection_eventid:
        EventID: 4697
    selection:
        ServiceFileName|re: '.*cmd.{0,5}(?:\/c|\/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\\"\{\d\}.+\-f.+\"'
    condition: selection and selection_eventid
falsepositives:
    - Unknown
level: high